---

- name: Make teamcity db user
  postgresql_user:
    name: "{{teamcity_db_user}}"
    password: "{{teamcity_db_password}}"
    role_attr_flags: CREATEDB,NOSUPERUSER
    login_host: 0.0.0.0
    login_user: docker
    login_password: docker

- name: Make teamcity db
  postgresql_db:
    name: "{{teamcity_db_name}}"
    encoding: "UTF-8"
    template: "template1"
    owner: "{{teamcity_db_user}}"
    login_host: 0.0.0.0
    login_user: docker
    login_password: docker
